const option = (days, dailyPrice, originalDailyPrice = null) => ({
  days,
  dailyPrice,
  originalDailyPrice,
  price: +(days * dailyPrice).toFixed(1),
  label: `${days}j`,
  priceLabel: `${dailyPrice.toFixed(1)} DH/j`,
  originalPriceLabel: originalDailyPrice ? `${originalDailyPrice.toFixed(1)} DH/j` : null,
});

export const unifiedPlans = [
  {
    id: "gratuit",
    label: "Gratuit",
    price: 0,
    period: null,
    activeListings: 1,
    durationDays: 7,
    stars: 1,
    professionalProfile: "-",
    verifiedBadge: "-",
    visibility: "Standard",
    statistics: "Vues",
    users: 1,
    boostsPerMonth: 0,
    support: "Centre d'aide",
    cta: "Publier gratuitement",
    subtitle: "Pour tester une annonce sans engagement",
    recommended: false,
    billingOptions: [option(7, 0)],
    features: [
      { text: "1 annonce active", included: true },
      { text: "Duree 7 jours", included: true },
      { text: "Visibilite standard", included: true },
      { text: "Statistiques de vues", included: true },
      { text: "Boutique verifiee", included: false },
    ],
  },
  {
    id: "basic",
    label: "Basic",
    price: 558,
    period: null,
    activeListings: 7,
    durationDays: 30,
    stars: 3,
    professionalProfile: "Profil pro",
    verifiedBadge: "-",
    visibility: "Amelioree",
    statistics: "Basiques",
    users: 1,
    boostsPerMonth: 0,
    support: "E-mail",
    cta: "Choisir Basic",
    subtitle: "Ameliorez la visibilite de votre annonce",
    recommended: false,
    billingOptions: [option(30, 18.6), option(14, 24.8)],
    features: [
      { text: "3 etoiles de visibilite", included: true },
      { text: "14j a 24.8 DH/j", included: true },
      { text: "30j a 18.6 DH/j", included: true },
      { text: "Statistiques basiques", included: true },
      { text: "Boutique verifiee", included: false },
    ],
  },
  {
    id: "pro",
    label: "Pro",
    price: 579,
    period: null,
    activeListings: 20,
    durationDays: 30,
    stars: 4,
    professionalProfile: "Vitrine boutique",
    verifiedBadge: "Inclus",
    visibility: "Prioritaire",
    statistics: "Completes",
    users: 2,
    boostsPerMonth: 1,
    support: "Prioritaire",
    cta: "Choisir Pro",
    subtitle: "Boutique verifiee, badge pro et outils business",
    recommended: true,
    billingOptions: [option(30, 19.3), option(14, 28.5), option(7, 41.2)],
    features: [
      { text: "4 etoiles de visibilite", included: true },
      { text: "Boutique verifiee incluse", included: true },
      { text: "Badge pro sur annonces", included: true },
      { text: "Stats business completes", included: true },
      { text: "1 boost inclus", included: true },
    ],
  },
  {
    id: "max",
    label: "Max",
    price: 1071,
    period: null,
    activeListings: 50,
    durationDays: 30,
    stars: 5,
    professionalProfile: "Vitrine premium",
    verifiedBadge: "Renforce",
    visibility: "Maximale",
    statistics: "Dashboard + recommandations",
    users: 5,
    boostsPerMonth: 3,
    support: "Prioritaire 24 h",
    cta: "Choisir Max",
    subtitle: "Visibilite maximale pour capter tous les acheteurs",
    recommended: false,
    promo: true,
    billingOptions: [option(30, 35.7, 42.0), option(14, 48.5, 57.1), option(7, 59.0, 65.5)],
    features: [
      { text: "5 etoiles de visibilite", included: true },
      { text: "Prix promo sur toutes les durees", included: true },
      { text: "Visibilite maximale", included: true },
      { text: "Boutique premium", included: true },
      { text: "3 boosts inclus", included: true },
    ],
  },
];

export const planComparisonRows = [
  { key: "stars", label: "Niveau", format: (plan) => `${plan.stars} etoile${plan.stars > 1 ? "s" : ""}` },
  { key: "price", label: "Prix", format: (plan) => plan.price === 0 ? "0 MAD" : `Des ${Math.min(...plan.billingOptions.map((o) => o.dailyPrice)).toFixed(1)} DH/j` },
  { key: "durationDays", label: "Durees", format: (plan) => plan.billingOptions.map((option) => option.label).join(" / ") },
  { key: "activeListings", label: "Annonces actives" },
  { key: "professionalProfile", label: "Profil professionnel" },
  { key: "verifiedBadge", label: "Badge verifie" },
  { key: "visibility", label: "Visibilite" },
  { key: "statistics", label: "Statistiques" },
  { key: "users", label: "Utilisateurs" },
  {
    key: "boostsPerMonth",
    label: "Boosts inclus",
    format: (plan) => plan.boostsPerMonth > 0 ? plan.boostsPerMonth : "-",
  },
  { key: "support", label: "Support" },
  { key: "cta", label: "Bouton" },
];

export const paymentMethods = [
  {
    id: "card",
    label: "Carte bancaire",
    description: "Validation immediate de l'abonnement.",
  },
  {
    id: "bank_transfer",
    label: "Virement bancaire",
    description: "Activation apres confirmation de la reference.",
  },
  {
    id: "cash",
    label: "Paiement cash",
    description: "Reservation du plan avec suivi administratif.",
  },
];

export const pricingPlans = {
  jobs: unifiedPlans,
  immobilier: unifiedPlans,
  vehicules: unifiedPlans,
  evenements: unifiedPlans,
  sante: unifiedPlans,
};
