// frontend/constants/pricingPlans.js
//
// Modèle hybride : Gratuit (7 jours) → Boost ponctuel (20 jours) → Pro (abonnement) → VIP (abonnement)

export const pricingPlans = {
  jobs: [
    {
      id: 'gratuit',
      label: 'Gratuit',
      price: 0,
      period: null,
      subtitle: 'Idéal pour démarrer',
      features: [
        { text: '1 offre active', included: true },
        { text: 'Visibilité standard', included: true },
        { text: 'Mise en avant', included: false },
        { text: 'Expiration 7 jours', included: true },
      ],
    },
    {
      id: 'boost',
      label: 'Boost',
      price: 39,
      period: 'offre',
      subtitle: 'Boostez une offre ponctuellement',
      features: [
        { text: '1 offre boostée', included: true },
        { text: 'Mise en avant 20 jours', included: true },
        { text: 'Visibilité prioritaire dans les résultats', included: true },
        { text: 'Sans engagement', included: true },
        { text: 'Badge entreprise vérifié', included: false },
      ],
    },
    {
      id: 'pro',
      label: 'Pro',
      price: 99,
      period: 'mois',
      subtitle: 'Pour les recruteurs actifs',
      recommended: true,
      features: [
        { text: '5 offres actives', included: true },
        { text: 'Mise en avant dans les résultats', included: true },
        { text: 'Badge entreprise vérifié', included: true },
        { text: 'Statistiques de vues', included: true },
        { text: 'Expiration 60 jours', included: true },
      ],
    },
    {
      id: 'vip',
      label: 'VIP',
      price: 249,
      period: 'mois',
      subtitle: 'Visibilité maximale',
      features: [
        { text: 'Offres illimitées', included: true },
        { text: 'Sponsoring en tête de liste', included: true },
        { text: 'Accès aux CVs des candidats', included: true },
        { text: 'Chat avec les candidats', included: true },
        { text: 'Statistiques détaillées', included: true },
        { text: 'Support prioritaire', included: true },
        { text: 'Expiration 90 jours', included: true },
      ],
    },
  ],

  immobilier: [
    {
      id: 'gratuit',
      label: 'Gratuit',
      price: 0,
      period: null,
      subtitle: 'Pour débuter',
      features: [
        { text: '2 annonces actives', included: true },
        { text: '3 photos par annonce', included: true },
        { text: 'Mise en avant', included: false },
        { text: 'Expiration 7 jours', included: true },
      ],
    },
    {
      id: 'boost',
      label: 'Boost',
      price: 59,
      period: 'annonce',
      subtitle: 'Boostez une annonce ponctuellement',
      features: [
        { text: '1 annonce boostée', included: true },
        { text: 'Mise en avant 20 jours', included: true },
        { text: 'Visibilité prioritaire dans les résultats', included: true },
        { text: '5 photos supplémentaires', included: true },
        { text: 'Sans engagement', included: true },
        { text: 'Badge agence vérifiée', included: false },
      ],
    },
    {
      id: 'pro',
      label: 'Pro',
      price: 149,
      period: 'mois',
      subtitle: 'Pour les agences actives',
      recommended: true,
      features: [
        { text: '10 annonces actives', included: true },
        { text: '10 photos par annonce', included: true },
        { text: 'Mise en avant dans les résultats', included: true },
        { text: 'Badge agence vérifiée', included: true },
        { text: 'Expiration 60 jours', included: true },
      ],
    },
    {
      id: 'vip',
      label: 'VIP',
      price: 349,
      period: 'mois',
      subtitle: 'Visibilité maximale',
      features: [
        { text: 'Annonces illimitées', included: true },
        { text: 'Photos & vidéos illimitées', included: true },
        { text: 'Sponsoring en tête de liste', included: true },
        { text: 'Accès prioritaire aux prospects', included: true },
        { text: 'Statistiques détaillées', included: true },
        { text: 'Support prioritaire', included: true },
        { text: 'Expiration 90 jours', included: true },
      ],
    },
  ],

  vehicules: [
    {
      id: 'gratuit',
      label: 'Gratuit',
      price: 0,
      period: null,
      subtitle: 'Pour essayer',
      features: [
        { text: '1 annonce active', included: true },
        { text: '4 photos par annonce', included: true },
        { text: 'Mise en avant', included: false },
        { text: 'Expiration 7 jours', included: true },
      ],
    },
    {
      id: 'boost',
      label: 'Boost',
      price: 39,
      period: 'annonce',
      subtitle: 'Boostez une annonce ponctuellement',
      features: [
        { text: '1 annonce boostée', included: true },
        { text: 'Mise en avant 20 jours', included: true },
        { text: 'Position prioritaire dans les résultats', included: true },
        { text: 'Sans engagement', included: true },
        { text: 'Badge vendeur vérifié', included: false },
      ],
    },
    {
      id: 'pro',
      label: 'Pro',
      price: 99,
      period: 'mois',
      subtitle: 'Pour les vendeurs actifs',
      recommended: true,
      features: [
        { text: '5 annonces actives', included: true },
        { text: '15 photos par annonce', included: true },
        { text: 'Annonces en tête de liste', included: true },
        { text: 'Badge vendeur vérifié', included: true },
        { text: 'Expiration 60 jours', included: true },
      ],
    },
    {
      id: 'vip',
      label: 'VIP',
      price: 249,
      period: 'mois',
      subtitle: 'Visibilité maximale',
      features: [
        { text: 'Annonces illimitées', included: true },
        { text: 'Photos & vidéos illimitées', included: true },
        { text: 'Remontée automatique', included: true },
        { text: 'Chat avec les acheteurs', included: true },
        { text: 'Statistiques détaillées', included: true },
        { text: 'Support prioritaire', included: true },
        { text: 'Expiration 90 jours', included: true },
      ],
    },
  ],
}